/* Reviewed English UI catalogue. Source documents retain their original language. */
window.AnodosEnglish = Object.freeze({
  "Навчання": "Learning",
  "Страхування": "Insurance",
  "Інструменти": "Tools",
  "Довідники": "References",
  "Мій прогрес": "My progress",
  "Мої документи": "My documents",
  "Середовище": "Workspace",
  "Обрати середовище": "Choose workspace",
  "РОЗУМІТИ. ДІЯТИ. ЗРОСТАТИ.": "UNDERSTAND. ACT. GROW.",
  "Анодос - головна": "Anodos - home",
  "Відкрити меню": "Open menu",
  "Закрити меню": "Close menu",
  "Основна навігація": "Main navigation",
  "Навігація простору": "Workspace navigation",
  "Пошук на сайті": "Search the site",
  "На початок сторінки": "Back to top",
  "Відкрити допоміжне меню": "Open tools menu",
  "Закрити допоміжне меню": "Close tools menu",
  "Робочі інструменти": "Professional tools",
  "РОБОЧІ ІНСТРУМЕНТИ": "PROFESSIONAL TOOLS",
  "Оцінка страхового договору": "Insurance policy assessment",
  "Короткий висновок і PDF BRITMARK": "Summary and BRITMARK PDF report",
  "Адреса в GPS-координати": "Address to GPS coordinates",
  "Знайти та скопіювати координати адреси": "Find and copy coordinates for an address",
  "Перевірка договорів": "Policy review",
  "Перевірити або порівняти договори": "Review or compare policies",
  "Акредитація в банках": "Bank accreditation",
  "Знайти страховиків для застави": "Find insurers for collateral",
  "Генератор опитувальників": "Questionnaire builder",
  "Підготувати опитувальник BritMark": "Create a BritMark questionnaire",
  "Рекомендація Клієнту": "Client recommendation",
  "Підготувати брокерський висновок": "Prepare a broker's assessment",
  "Пошук контактів ДМів": "Decision-maker contact search",
  "OSINT-аналітика": "OSINT research",
  "Написання котирувань": "Quotation drafting",
  "Автоматичне заповнення опитувальника": "Automatic questionnaire completion",
  "Навчальні модулі": "Learning modules",
  "Особистий прогрес": "Personal progress",
  "Страхові продукти": "Insurance products",
  "Закон про страхування": "Insurance law",
  "Страховий словник": "Insurance glossary",
  "Оцінка договору": "Policy assessment",
  "Адреса в GPS": "Address to GPS",
  "Усі інструменти": "All tools",
  "Знання та інструменти для роботи зі страхуванням.": "Knowledge and tools for insurance professionals.",
  "Професійне навчання": "Professional learning",
  "Знання, що": "Knowledge that",
  "перетворюються": "turns into",
  "на рішення.": "decisions.",
  "Від основ страхування до впевненої роботи зі складними ризиками.": "From insurance fundamentals to confident decisions on complex risks.",
  "Почати навчання": "Start learning",
  "Страхові рішення": "Insurance solutions",
  "Кожен ризик": "Every risk",
  "потребує": "needs its",
  "свого рішення.": "own solution.",
  "Знайдіть потрібне покриття, розберіться в умовах і підготуйте відповідь Клієнту.": "Find the right cover, understand the terms and prepare your response to the client.",
  "Знайти рішення": "Find a solution",
  "Більше ясності.": "More clarity.",
  "Менше": "Less",
  "рутинної роботи.": "routine work.",
  "Договори, опитувальники та дослідження компаній в одному робочому просторі.": "Policies, questionnaires and company research in one workspace.",
  "Оцінити договір": "Assess a policy",
  "Теми першого екрана": "Featured topics",
  "Зупинити або відновити відео": "Pause or resume video",
  "Рух фону": "Background motion",
  "Основні напрями": "Explore Anodos",
  "Розвивайте страхову експертизу": "Build your insurance expertise",
  "Знаходьте рішення для ризиків": "Find solutions for risks",
  "Зосередьтеся на головному": "Focus on what matters",
  "Від ситуації до рішення": "From a situation to a solution",
  "З чим працюємо сьогодні?": "What are we working on today?",
  "Опишіть ситуацію Клієнта": "Describe your client's situation",
  "Опишіть ситуацію простими словами, а Anodos підкаже, де шукати відповідь.": "Describe the situation in plain language and Anodos will help you find an answer.",
  "Від знань до практики": "From knowledge to practice",
  "Ваш простір рішень": "Your solutions workspace",
  "Шість напрямів для розвитку вашої експертизи.": "Six areas to develop your expertise.",
  "Матеріали та інструменти для кожного виду страхування.": "Resources and tools for each type of insurance.",
  "Для щоденної роботи": "For your daily work",
  "Ваша увага - на рішеннях.": "Focus on decisions.",
  "Інструменти Анодус допоможуть із рештою.": "Anodos tools will help with the rest.",
  "Сильні умови, обмеження виплати та конкретні рекомендації.": "Strong policy terms, payment limitations and specific recommendations.",
  "Перевірити умови": "Review the terms",
  "Порівняння договорів": "Policy comparison",
  "Зіставлення покриття, винятків і параметрів страхування.": "Compare cover, exclusions and policy terms.",
  "Порівняти договори": "Compare policies",
  "Опитувальники": "Questionnaires",
  "Підготовка форм для збору інформації про ризик.": "Prepare forms to collect risk information.",
  "Підготувати форму": "Prepare a form",
  "Координати об'єкта для оцінки ризику та роботи з картами.": "Location coordinates for risk assessment and mapping.",
  "Знайти координати": "Find coordinates",
  "Страховики для заставного майна та вимоги банків.": "Insurers for collateral and bank requirements.",
  "Переглянути акредитацію": "View accreditation",
  "Дослідження компаній": "Company research",
  "Бізнес, власність та активи з посиланнями на джерела.": "Business, ownership and assets with links to sources.",
  "Відкрити OSINT": "Open OSINT",
  "Майно": "Property",
  "Відповідальність": "Liability",
  "Вантажі": "Cargo",
  "Воєнні ризики": "War risks",
  "Будівельно-монтажні ризики": "Construction and erection risks",
  "БМР": "CAR / EAR",
  "Named perils і all risks": "Named perils and all risks",
  "Шкода третім особам": "Third-party injury and damage",
  "Маршрут, товар, документи": "Route, goods and documents",
  "Застереження і межі покриття": "Clauses and limits of cover",
  "Проєкт, роботи, об'єкт": "Project, works and site",
  "Директори та посадові особи": "Directors and officers",
  "Розрізняти модель покриття, читати структуру договору і бачити головні винятки.": "Distinguish coverage models, understand policy structure and identify key exclusions.",
  "Визначати застраховану діяльність, потерпілу третю особу, вимогу і межі території.": "Identify the insured activity, injured third party, claim and territorial limits.",
  "Читати договір перевезення через вантаж, маршрут, транспортний документ і спеціальні умови.": "Understand cargo cover through the goods, route, transport document and special terms.",
  "Відрізняти воєнне покриття від воєнного винятку і правильно ставити питання андеррайтеру.": "Distinguish war cover from war exclusions and ask the underwriter the right questions.",
  "Розуміти межі страхування будівельно-монтажних робіт: що є об'єктом, які роботи покриті і де починаються винятки.": "Understand construction and erection cover: the insured property, covered works and exclusions.",
  "Розуміти, кого захищає D&O, які вимоги можуть бути покриті і як відрізнити особисту відповідальність посадової особи від ризику компанії.": "Understand whom D&O protects, which claims may be covered and how personal liability differs from company risk.",
  "Статті, робочий чекліст та спеціалізовані інструменти для щоденної роботи з продуктом.": "Articles, a working checklist and specialist tools for everyday product work.",
  "Статті та кейси": "Articles and cases",
  "Робочий чекліст": "Working checklist",
  "Нормативна База": "Regulatory sources",
  "Державна програма компенсації": "State compensation programme",
  "Застереження Munich Re": "Munich Re clauses",
  "Відео-презентація": "Video presentation",
  "Короткий конспект": "Summary notes",
  "Теми модуля": "Module topics",
  "Задачі": "Exercises",
  "Тести до ЗУпС": "Insurance law tests",
  "Тести": "Tests",
  "Тест": "Test",
  "Навчальні матеріали": "Learning materials",
  "Робочі матеріали": "Work resources",
  "Назад": "Back",
  "Назад до продуктів": "Back to products",
  "Головна": "Home",
  "Продукти": "Products",
  "Прогрес": "Progress",
  "Програма": "Programme",
  "Локальний режим": "Local mode",
  "Локальний прогрес": "Local progress",
  "Без входу": "No sign-in required",
  "Прогрес зберігається на цьому пристрої. Пошта не потрібна.": "Your progress is saved on this device. No email is required.",
  "Прогрес за продуктами": "Progress by product",
  "Редагувати профіль": "Edit profile",
  "Фото": "Photo",
  "Додати фото": "Add photo",
  "ПІБ": "Full name",
  "Зберегти": "Save",
  "Скасувати": "Cancel",
  "Профіль": "Profile",
  "Співробітник": "Employee",
  "Редагувати": "Edit",
  "Експорт неточностей": "Export reported inaccuracies",
  "Словник": "Glossary",
  "Майнове страхування": "Property insurance",
  "Українські пояснення, англійські відповідники та практичні приклади.": "Ukrainian explanations, English equivalents and practical examples.",
  "Пошук у словнику": "Search the glossary",
  "Термін, скорочення або ситуація": "Term, abbreviation or situation",
  "Тема словника": "Glossary topic",
  "Усі теми": "All topics",
  "Згорнути список": "Collapse list",
  "Список термінів": "Term list",
  "Пояснення терміна": "Term explanation",
  "Нічого не знайдено": "Nothing found",
  "Не вдалося завантажити словник": "Could not load the glossary",
  "Спробуйте коротший термін, англійське скорочення або виберіть усі теми.": "Try a shorter term, an English abbreviation or select all topics.",
  "Оновіть сторінку, щоб завантажити терміни.": "Reload the page to load the terms.",
  "Показати всі терміни": "Show all terms",
  "Обрати термін зі словника": "Select a glossary term",
  "На практиці:": "In practice:",
  "Пов'язані терміни": "Related terms",
  "Джерела та контекст": "Sources and context",
  "ЗУпС": "Insurance law",
  "Закон України «Про страхування»": "Law of Ukraine on Insurance",
  "Закон України про страхування": "Law of Ukraine on Insurance",
  "Пошук по тексту закону, преамбулі та прикінцевих положеннях.": "Search the law, its preamble and final provisions.",
  "Відкрити пошук": "Open search",
  "Пошук": "Search",
  "Пошук у законі": "Search the law",
  "Згорнути пошук": "Collapse search",
  "Введіть запит для пошуку": "Enter a search query",
  "Джерела": "Sources",
  "Джерело": "Source",
  "Очистити": "Clear",
  "Зупинити": "Stop",
  "Завантажити PDF": "Download PDF",
  "Завантажити DOCX": "Download DOCX",
  "Завантажити PDF ↓": "Download PDF ↓",
  "Новий пошук": "New search",
  "Спробувати ще раз": "Try again",
  "Обсяг": "Scope",
  "Банк": "Bank",
  "Страхова компанія": "Insurance company",
  "Anodos · банки": "Anodos · banks",
  "Акредитація страхових компаній": "Insurance company accreditation",
  "Дані поки недоступні.": "Data is not available yet.",
  "Заставне майно та нерухомість · офіційні джерела банків і страховиків": "Collateral and real estate · official bank and insurer sources",
  "Пошук і пояснення статусів": "Search and status key",
  "Наприклад: Кредит Дніпро або Південний": "For example: Credit Dnipro or Pivdenny",
  "Наприклад: УНІКА або ARX": "For example: UNIQA or ARX",
  "Лише банки з підтвердженням": "Only banks with confirmed accreditation",
  "Умовні позначення": "Key",
  "підтверджено для майна": "confirmed for property",
  "є обмеження": "restrictions apply",
  "- публічного підтвердження не знайдено": "- no public confirmation found",
  "Підтверджено для майна": "Confirmed for property",
  "Підтверджено для майна з обмеженнями": "Confirmed for property with restrictions",
  "Матриця акредитації для майна. Прокручуйте, щоб переглянути всі банки та страхові компанії.": "Property accreditation matrix. Scroll to see all banks and insurance companies.",
  "За цими фільтрами нічого не знайдено. Спробуйте коротшу назву або змініть фільтри.": "No matches for these filters. Try a shorter name or change the filters.",
  "Відкрити офіційне джерело ↗": "Open the official source ↗",
  "Заставне майно": "Collateral property",
  "Вставте адресу з містом, вулицею та номером будинку.": "Enter the city, street and building number.",
  "Пошук координат": "Coordinate search",
  "Адреса": "Address",
  "Наприклад: Україна, Київ, вулиця Хрещатик, 36": "For example: Ukraine, Kyiv, 36 Khreshchatyk Street",
  "Для села або селища додайте область; для адреси за кордоном - країну.": "For a village or town, include the region; for an address abroad, include the country.",
  "Після натискання кнопки адреса передається сервісу Photon для пошуку на карті. Вставляйте лише адресу, без імен та інших особистих даних.": "When you click the button, the address is sent to Photon for a map search. Enter only an address, without names or other personal data.",
  "Знайдені місця": "Places found",
  "Координати позначають точку об'єкта на карті, яка може не збігатися з входом до будинку. Перевірте місце на карті перед використанням.": "Coordinates mark a point on the map that may differ from the building entrance. Check the location on the map before using it.",
  "Пошук:": "Search:",
  ". Дані: ©": ". Data: ©",
  "учасники OpenStreetMap": "OpenStreetMap contributors",
  "Потрібен інтернет. Точність залежить від повноти адреси та даних карти.": "An internet connection is required. Accuracy depends on the address and available map data.",
  "Для пошуку координат увімкніть JavaScript у браузері.": "Enable JavaScript in your browser to search for coordinates.",
  "ПОШУК КОНТАКТІВ ДМІВ": "DECISION-MAKER CONTACT SEARCH",
  "це приватний інструмент. введіть пароль": "This is a private tool. Enter your password.",
  "Пароль Anodos Pro": "Anodos Pro password",
  "Пароль": "Password",
  "Відкрити інструмент": "Open tool",
  "Закрити доступ": "Lock tool",
  "Знайдіть діловий контакт людини, яка приймає рішення. Ім’я та компанія - на вході. Телефони, email і джерела - у результаті.": "Find a decision-maker's business contact details. Enter a name and company to get phone numbers, email addresses and sources.",
  "Чий контакт шукаємо?": "Whose contact details are you looking for?",
  "Ім’я та прізвище": "First and last name",
  "Ім’я Прізвище": "First name Last name",
  "Назва компанії": "Company name",
  "Компанія або група": "Company or group",
  "Додати відому сторінку": "Add a known page",
  "Сайт компанії або відома сторінка з контактом": "Company website or a known contact page",
  "Погоджуюся передати ім’я та назву компанії пошуковим сервісам для пошуку публічних ділових контактів.": "I agree to share the name and company with search services to find public business contact details.",
  "Знайти контакти →": "Find contacts →",
  "Насамперед телефони. Зазвичай кілька хвилин.": "Phone numbers first. Usually takes a few minutes.",
  "РЕЗУЛЬТАТ ПОШУКУ": "SEARCH RESULT",
  "Зберегти результат ↓": "Save result ↓",
  "Від номера до джерела": "From number to source",
  "Для кожного контакту показуємо сторінку і фрагмент, у якому його опубліковано. Загальні телефони компанії наведено окремо.": "Each contact includes the page and excerpt where it was published. General company numbers are listed separately.",
  "Актуальність має значення": "Up-to-date information matters",
  "Старі джерела позначаємо. Якщо ділового номера людини не підтверджено, прямо про це повідомляємо.": "Older sources are labelled. If a person's business number cannot be confirmed, we state this clearly.",
  "Пошук працює з відкритими діловими сторінками та PDF у межах доступності пошукових сервісів. Повне охоплення інтернету не гарантується. Залишайте вкладку відкритою. Сервіс залежить від доступності комп’ютера оператора Anodos.": "The search uses public business pages and PDFs available through search services. Full web coverage is not guaranteed. Keep this tab open. The service depends on the Anodos operator's computer being available.",
  "OSINT-АНАЛІТИКА": "OSINT RESEARCH",
  "ДОСЛІДЖЕННЯ КОМПАНІЙ": "COMPANY RESEARCH",
  "Бізнес, структура власності та активи компанії. Результат - PDF із висновками й джерелами.": "A company's business, ownership and assets. Get a PDF with findings and sources.",
  "Яку компанію дослідити?": "Which company would you like to research?",
  "Назва компанії або групи": "Company or group name",
  "Наприклад, Кернел або Метінвест": "For example, Kernel or Metinvest",
  "Знайти компанію": "Find company",
  "Додати сайт компанії": "Add company website",
  "Публічна HTTPS-адреса": "Public HTTPS address",
  "Сайт допоможе уточнити компанію або дослідити її, якщо назву не знайдено.": "A website helps identify the company or research it if the name is not found.",
  "Дослідити цей сайт": "Research this website",
  "Погоджуюся на пошук назви у відкритих джерелах та обробку й збереження дослідження на сервері Anodos.": "I agree to searching the name in public sources and processing and storing the research on the Anodos server.",
  "Пілот шукає у Вікіпедії українською та англійською, читає зовнішні джерела й сторінки компанії. ЄДРПОУ, платні реєстри та суцільний вебпошук поки не підключені.": "The pilot searches Ukrainian and English Wikipedia, external sources and company pages. EDRPOU, paid registers and comprehensive web search are not connected yet.",
  "Оберіть саме потрібну компанію": "Select the correct company",
  "Перевірте опис: пошук також може знаходити людей або однойменні організації.": "Check the description: results may include people or organisations with similar names.",
  "Почати дослідження": "Start research",
  "ПОПЕРЕДНІЙ ЗВІТ": "PRELIMINARY REPORT",
  "Що потрапить у PDF": "What the PDF includes",
  "Огляд бізнесу, юридичні особи й власники, активи, фінанси, партнери, ризики та питання для перевірки.": "Business overview, legal entities and owners, assets, finances, partners, risks and questions to verify.",
  "Як читати результат": "How to read the result",
  "Твердження джерел та припущення позначаються окремо. Якщо відомостей недостатньо, це буде прямо вказано. Пілот не гарантує повноти структури чи активів.": "Source statements and assumptions are labelled separately. Missing information is stated explicitly. The pilot does not guarantee complete ownership or asset coverage.",
  "Обробка виконується на комп’ютері оператора Anodos і залежить від його доступності. Залишайте цю вкладку відкритою. Дослідження може тривати кілька хвилин; PDF зберігайте на свій пристрій.": "Processing runs on the Anodos operator's computer and depends on its availability. Keep this tab open. Research may take a few minutes; save the PDF to your device.",
  "BRITMARK · ПЕРЕВІРКА УМОВ": "BRITMARK · POLICY REVIEW",
  "Зрозумійте свій": "Understand your",
  "страховий договір.": "insurance policy.",
  "Що захищає ваші інтереси, що може обмежити виплату та які зміни варто обговорити зі страховиком.": "See what protects your interests, what may limit a claim payment and which changes to discuss with your insurer.",
  "Додайте договір": "Add your policy",
  "Разом із правилами, програмою та додатками, на які він посилається.": "Include the wording, programme and appendices it refers to.",
  "Вибрати файли": "Choose files",
  "або перетягніть їх сюди": "or drag them here",
  "Договір і додатки": "Policy and appendices",
  "PDF, Word, Excel, текст або фото. До 8 файлів, 20 МБ кожен, 60 МБ разом. Великі пакети опрацьовуються частинами та отримують єдиний звіт.": "PDF, Word, Excel, text or images. Up to 8 files, 20 MB each, 60 MB in total. Large packages are processed in parts and receive one report.",
  "Погоджуюсь на аналіз документів": "I agree to document analysis",
  "Погоджуюся на хмарний аналіз документів і передачу їх копій BRITMARK для збереження та перевірки.": "I agree to cloud analysis of the documents and sharing copies with BRITMARK for storage and review.",
  "Як обробляються документи": "How documents are processed",
  "Файли й розпізнаний текст передаються на захищений сервер Cloudflare. Workers AI аналізує текст. Копії завантажуються до приватного архіву BRITMARK, коли комп’ютер доступний. Хмарний аналіз працює незалежно від цього.": "Files and extracted text are sent to a secure Cloudflare server. Workers AI analyses the text. Copies are uploaded to BRITMARK's private archive when its computer is available. Cloud analysis works independently.",
  "Доступ до результату має кожен, кому ви передасте приватне посилання. Хмарні копії видаляються через 30 днів; локальний архів BRITMARK зберігається довше. Не завантажуйте матеріали, на передачу яких не маєте права.": "Anyone with the private link can access the result. Cloud copies are deleted after 30 days; BRITMARK's local archive is retained longer. Only upload materials you are authorised to share.",
  "Отримати оцінку": "Get an assessment",
  "Отримати оцінку →": "Get an assessment →",
  "Додати договір у чергу →": "Add policy to queue →",
  "Скопіювати приватне посилання": "Copy private link",
  "Збережіть його, щоб повернутися до результату протягом 30 днів.": "Save it to return to your result within 30 days.",
  "Перевірити інший договір": "Review another policy",
  "ВАША ОЦІНКА": "YOUR ASSESSMENT",
  "Ми проаналізуємо ваш договір страхування та підкажемо, на що звернути увагу.": "We will analyse your insurance policy and highlight what to pay attention to.",
  "Умови договору": "Policy terms",
  "простою мовою.": "in plain language.",
  "Висновок міститиме конкретні пояснення та посилання на відповідні фрагменти вашого договору.": "The assessment will include specific explanations and references to relevant passages in your policy.",
  "Сильні умови": "Strong policy terms",
  "Рекомендовані покращення": "Suggested improvements",
  "Питання для уточнення": "Questions to clarify",
  "Правила залежать від виду страхування. Відсутність документа позначаємо як обмеження оцінки.": "Rules depend on the type of insurance. Missing documents are flagged as limitations of the assessment.",
  "Автоматична оцінка допомагає підготуватися до розмови зі страховим фахівцем.": "The automated assessment helps you prepare for a discussion with an insurance professional.",
  "Сервіс тимчасово недоступний.": "The service is temporarily unavailable.",
  "Не вдалося перевірити доступність сервісу. Спробуємо знову через хвилину.": "Could not check service availability. We will try again in a minute.",
  "Сервіс готується до запуску. Завантаження поки недоступне.": "The service is being prepared. Uploads are not available yet.",
  "Спочатку додайте договір.": "Add a policy first.",
  "Підтвердьте обробку документів.": "Confirm document processing.",
  "Додайте не більше 8 файлів.": "Add no more than 8 files.",
  "Кожен файл має бути непорожнім, до 20 МБ; увесь пакет до 60 МБ.": "Each file must be non-empty and no larger than 20 MB; the whole package must not exceed 60 MB.",
  "Файли мають однакову назву. Перейменуйте їх перед завантаженням.": "Some files have identical names. Rename them before uploading.",
  "Посилання скопійовано": "Link copied",
  "Скачати PDF ↓": "Download PDF ↓",
  "Що погодити:": "What to agree:",
  "Фрагмент договору": "Policy excerpt",
  "Що варто покращити": "What to improve",
  "Що вже працює на вашу користь": "What already works in your favour",
  "Встановлені умови": "Identified terms",
  "Що потрібно уточнити": "What to clarify",
  "Межі перевірки": "Review limitations",
  "Автоматична оцінка може містити пропуски. Перед погодженням змін звірте рекомендації з оригіналом і страховим фахівцем.": "The automated assessment may contain omissions. Check recommendations against the original and with an insurance professional before agreeing to changes.",
  "Професійний інструмент Anodos Pro.": "An Anodos Pro professional tool.",
  "введіть пароль": "Enter your password",
  "Банки": "Banks",
  "Договори": "Policies",
  "Anodos · робочий інструмент": "Anodos · professional tool",
  "Anodos · договори": "Anodos · policies",
  "Опишіть потрібний опитувальник та отримайте порожню форму BritMark для заповнення.": "Describe the questionnaire you need and get a blank BritMark form to complete.",
  "Який опитувальник потрібен?": "Which questionnaire do you need?",
  "Створити порожню форму": "Create a blank form",
  "Порожня форма створюється у браузері без передачі даних.": "The blank form is created in your browser without sending any data.",
  "Один опис — структурований страховий запит": "One description - a structured insurance enquiry",
  "База охоплює майно, комерційну нерухомість, елеватори, енергетику, вантажі, будівельно-монтажні роботи, відповідальність, кіберризики та інші профілі.": "The library covers property, commercial real estate, grain elevators, energy, cargo, construction and erection, liability, cyber risks and other profiles.",
  "Перевірка договору страхування майна": "Property insurance policy review",
  "Завантаж договір і супровідні документи. Anodos знайде ризикові умови та сформує список конкретних правок із посиланнями на текст.": "Upload the policy and supporting documents. Anodos will identify risky terms and suggest specific changes with references to the text.",
  "Перевірити договір": "Review a policy",
  "Локальна модель Anodos, без оплати за ШІ-запит.": "Anodos local model, with no charge per AI request.",
  "Mac Anodos читає оригінали, аналізує договір і зберігає PDF. Після повного завантаження вкладку можна закрити. Повернися за приватним посиланням нижче. Аналіз може тривати кілька хвилин і не зупиняється через одну хвилину. Якщо Mac вимкнений, збережена перевірка продовжиться після запуску сервісу.": "The Anodos Mac reads the originals, analyses the policy and saves the PDF. Once the upload is complete, you can close the tab and return using the private link below. Analysis may take several minutes and will not stop after one minute. If the Mac is off, the saved review will resume when the service starts.",
  "Додай договір": "Add a policy",
  "Перетягни або вибери файли": "Drag files here or choose files",
  "Вибрати договір": "Choose a policy",
  "Вибрати договори": "Choose policies",
  "Читаються PDF, Word, ODT, RTF, текстові файли, таблиці та зображення. Скановані PDF і фото розпізнаються OCR українською та англійською.": "Supports PDF, Word, ODT, RTF, text files, spreadsheets and images. Scanned PDFs and photos are processed with Ukrainian and English OCR.",
  "Оригінали, розпізнаний текст, результат і PDF зберігаються на комп’ютері оператора Anodos. Читання та створення PDF виконуються на Mac, незалежно від вкладки. Файли шифруються у браузері перед передачею; Cloudflare передає зашифровані дані без хмарного архіву договорів. Аналіз виконує локальна Ollama, без зовнішньої AI-моделі. Це не обробка лише на вашому пристрої.": "Originals, extracted text, results and PDFs are stored on the Anodos operator's computer. Reading and PDF generation run on the Mac independently of this tab. Files are encrypted in your browser before transfer; Cloudflare relays encrypted data without a cloud policy archive. Analysis uses local Ollama without an external AI model. Processing is not limited to your own device.",
  "Маю право передати ці документи та погоджуюся на їх обробку і зберігання оператором Anodos, включно з оригіналами й результатом.": "I am authorised to share these documents and agree to their processing and storage by the Anodos operator, including the originals and results.",
  "Архів не видаляється автоматично. Не додавай зайві персональні дані. До 12 файлів по 30 МБ, до 120 МБ на пакет і 600 тисяч символів тексту; пакет не обрізається заради межі. Закриття вкладки під час передачі файлів потребуватиме повторного вибору тих самих оригіналів.": "The archive is not deleted automatically. Avoid unnecessary personal data. Up to 12 files of 30 MB each, 120 MB per package and 600,000 text characters; packages are not truncated to meet the limit. If you close the tab during upload, you will need to select the same original files again.",
  "Місто, вулиця, номер будинку та корпус": "City, street, building number and unit",
  "Наприклад: елеватор, разове вантажоперевезення, будівельно-монтажні роботи або відповідальність за якість продукції": "For example: grain elevator, single cargo shipment, construction works or product liability",
  "Режим роботи з договорами": "Policy review mode",
  "Додати договір для перевірки": "Add a policy for review",
  "Пакет": "Package",
  "Попередній пакет": "Previous package",
  "Пакет оновлення": "Renewal package",
  "Не аналізувати": "Exclude from analysis",
  "Тип": "Type",
  "Основний договір": "Main policy",
  "Додаткова угода": "Endorsement",
  "Додаток / графік": "Appendix / schedule",
  "Заява": "Application",
  "Таблиця": "Spreadsheet",
  "Сервіс повернув некоректну відповідь. Спробуйте пізніше.": "The service returned an invalid response. Try again later.",
  "У відповіді немає придатних координат. Уточніть адресу або спробуйте пізніше.": "No usable coordinates were returned. Refine the address or try again later.",
  "Вставте адресу з назвою міста та вулиці.": "Enter an address with a city and street name.",
  "Залиште лише адресу, до 500 символів.": "Enter only the address, up to 500 characters.",
  "Забагато запитів. Зачекайте хвилину та спробуйте ще раз.": "Too many requests. Wait a minute and try again.",
  "Зачекайте кілька секунд перед наступним пошуком.": "Wait a few seconds before searching again.",
  "Сервіс тимчасово обмежив пошук. Зачекайте хвилину та спробуйте ще раз.": "The service has temporarily limited searches. Wait a minute and try again.",
  "Сервіс пошуку тимчасово недоступний. Спробуйте пізніше.": "The search service is temporarily unavailable. Try again later.",
  "Шукаю...": "Searching...",
  "Координати адреси": "Address coordinates",
  "Можливі збіги": "Possible matches",
  "Збігаються назви міста, вулиці та номер будинку. Звірте повну адресу нижче.": "The city, street and building number match. Check the full address below.",
  "Пошук не визначив єдину адресу. Це можливі збіги: звірте населений пункт, вулицю та номер будинку перед копіюванням.": "The search did not identify a unique address. Check the city, street and building number in these possible matches before copying.",
  "Адреса з номером будинку": "Address with building number",
  "Приблизне розташування": "Approximate location",
  "Номер будинку не визначено. Це точка вулиці, населеного пункту або об'єкта, а не підтверджене місце потрібного будинку.": "The building number was not identified. This is a street, town or landmark point, not the confirmed location of the requested building.",
  "GPS: широта, довгота": "GPS: latitude, longitude",
  "Скопіювати координати": "Copy coordinates",
  "Координати скопійовано.": "Coordinates copied.",
  "Координати виділено. Оберіть «Копіювати» або натисніть Ctrl+C / ⌘C.": "Coordinates selected. Choose Copy or press Ctrl+C / ⌘C.",
  "Відкрити на карті": "Open on map",
  "Карта містить кілька близьких точок за цією адресою: будівлю, входи або установи всередині. Вище показана точка будівлі, якщо вона є в результатах, або перший збіг карти. Інші точки можна перевірити нижче.": "The map has several nearby points at this address: the building, entrances or organisations inside. The building point is shown above when available, otherwise the first map match. Check the other points below.",
  "Вставте адресу довжиною від 3 до 500 символів.": "Enter an address between 3 and 500 characters long.",
  "Немає інтернету. Підключіться до мережі та повторіть пошук.": "You are offline. Connect to the internet and search again.",
  "Адреса в GPS-координати - Анодос": "Address to GPS coordinates - Anodos",
  "Оцінка страхового договору - BRITMARK / Anodos": "Insurance policy assessment - BRITMARK / Anodos",
  "Пошук контактів ДМів - Anodos": "Decision-maker contact search - Anodos",
  "OSINT-аналітика - Anodos": "OSINT research - Anodos",
  "Контакти осіб, які ухвалюють рішення, та джерела для перевірки.": "Decision-maker contacts and sources for verification.",
  "Бізнес, власність та активи компанії з посиланнями на джерела.": "A company's business, ownership and assets with source links.",
  "Підготовка страхових котирувань на основі матеріалів запиту.": "Prepare insurance quotations from enquiry materials.",
  "Заповнення форми на основі наданих документів та даних.": "Complete a form using the supplied documents and data.",
  "Завантаж два або більше пакетів документів, перевір їхні ролі та сформуй порівняльну таблицю. Сумнівні або конфліктні дані система позначить окремо.": "Upload two or more document packages, check their roles and create a comparison table. Uncertain or conflicting data is flagged separately.",
  "Додати договори": "Add policies",
  "Додай договори": "Add policies",
  "На телефоні натисни кнопку й вибери договори у «Файлах». На комп’ютері їх також можна перетягнути.": "On your phone, tap the button and choose policies from Files. On a computer, you can also drag them here.",
  "Порівняти": "Compare",
  "Шукаю адресу на карті...": "Searching for the address on the map...",
  "Адресу не знайдено. Перевірте написання, додайте область або країну. Спробуйте прибрати поштовий індекс чи номер квартири.": "Address not found. Check the spelling and add a region or country. Try removing the postcode or apartment number.",
  "Пошук триває надто довго. Спробуйте ще раз.": "The search is taking too long. Try again.",
  "Не вдалося з'єднатися із сервісом пошуку. Перевірте інтернет або спробуйте пізніше.": "Could not connect to the search service. Check your connection or try again later.",
  "Продукт": "Product",
  "Стаття BritMark": "BritMark article",
  "Нормативна база": "Regulatory sources",
  "Державна програма": "State programme",
  "Покрокова інструкція": "Step-by-step guide",
  "Калькулятор компенсації": "Compensation calculator",
  "Нічого точного не знайшов. Спробуйте коротше: компенсація премії, воєнні ризики, франшиза, вантажі, БМР.": "No exact matches. Try a shorter query: premium compensation, war risks, deductible, cargo or construction.",
  "воєнні ризики": "war risks",
  "компенсація премії": "premium compensation",
  "майно": "property",
  "договір": "policy",
  "відповідальність": "liability",
  "вантажі": "cargo",
  "будівельно-монтажні ризики": "construction and erection risks",
  "закон": "law",
  "Завершити тест": "Finish test",
  "Почати тест": "Start test",
  "Пройти тест": "Take test",
  "Повторити тест": "Retake test",
  "Перевірити відповідь": "Check answer",
  "Відкрити матеріал": "Open resource",
  "Відкрити матеріали": "Open resources",
  "Анодос (Άνοδος)": "Anodos (Ανοδος)",
  "Анодос (Άνοδος) — українська вебплатформа для професійного навчання, тестів і робочих інструментів у страхуванні.": "Anodos - a platform for professional insurance learning, tests and practical tools.",
  "Українська вебплатформа для професійного навчання у страхуванні: навчальні матеріали, тести, аналітика прогресу та робочі інструменти.": "A platform for professional insurance learning: resources, tests, progress tracking and practical tools.",
  "Професійне навчання, тести та робочі інструменти для страхування.": "Professional learning, tests and practical insurance tools.",
  "Анодос (Άνοδος) — платформа для навчання у страхуванні": "Anodos - an insurance learning platform",
  "Вставте адресу, знайдіть GPS-координати, скопіюйте їх або відкрийте місце на карті.": "Enter an address, find GPS coordinates, copy them or open the location on a map.",
  "Завантажте страховий договір, отримайте зрозумілу оцінку умов і PDF із рекомендаціями BRITMARK.": "Upload an insurance policy for a clear assessment of its terms and a PDF with BRITMARK recommendations."
});
